import CalculatorOutput from "@/components/CalculatorOutput/CalculatorOutput";
import LayoutComponent from "@/components/Layout/Layout";
import styles from "@/styles/Home.module.css";
import Head from "next/head";

export default function ResultPage() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Result - Calculator App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <LayoutComponent>
          <CalculatorOutput />
        </LayoutComponent>
      </main>
    </div>
  );
}
